services:
  essentia:
    image: ghcr.io/elijahjero/essentiadlp:latest
    ports:
      - "8182:8182"
    volumes:
      - essentia-data:/data
    environment:
      DataDirectory: /data
      Python: python3
      AnalyzerScript: /app/analyzer/tag_library.py
      ModelsDirectory: /app/analyzer/models

volumes:
  essentia-data:
